export const pricingContent = {
  title: "Tarifs transparents, ROI immédiat",
  subtitle: "Une amende REP peut atteindre 150 000 €. Klover vous revient à moins d'un café par jour.",
  plans: [
    {
      id: "free",
      name: "Free",
      badge: null,
      monthlyPrice: 0,
      annualPrice: 0,
      description: "Pour découvrir Klover et évaluer votre risque REP.",
      featured: false,
      cta: { label: "Commencer gratuitement", href: "/auth/v2/register" },
      features: [
        "Jusqu'à 50 références classifiées",
        "1 éco-organisme (CITEO ou LEKO)",
        "Classification automatique",
        "Import CSV",
        "Support communautaire",
      ],
    },
    {
      id: "starter",
      name: "Starter",
      badge: null,
      monthlyPrice: 49,
      annualPrice: 39,
      description: "Pour les e-commerçants qui veulent être conformes sans prise de tête.",
      featured: false,
      cta: { label: "Commencer", href: "/auth/v2/register?plan=starter" },
      features: [
        "Jusqu'à 500 références classifiées",
        "1 éco-organisme (CITEO ou LEKO)",
        "Déclarations mensuelles PDF",
        "Export des données",
        "Import CSV illimité",
        "Support par email",
      ],
    },
    {
      id: "growth",
      name: "Growth",
      badge: "Populaire",
      monthlyPrice: 149,
      annualPrice: 119,
      description: "Le choix de 80 % de nos clients. Conformité totale, zéro stress.",
      featured: true,
      cta: { label: "Commencer", href: "/auth/v2/register?plan=growth" },
      features: [
        "Jusqu'à 10 000 références classifiées",
        "Tous les éco-organismes (CITEO, LEKO, Ecomaison…)",
        "Rapports conformité prêts à soumettre",
        "Connexion Shopify / WooCommerce",
        "Détection automatique barèmes 2026",
        "Alertes dépassement de seuils",
        "Support prioritaire 24h",
        "Évitez jusqu'à 150 000 € d'amende REP",
      ],
    },
    {
      id: "enterprise",
      name: "Enterprise",
      badge: "Sur mesure",
      monthlyPrice: null,
      annualPrice: null,
      description: "Pour les groupes multi-entités avec des besoins spécifiques.",
      featured: false,
      cta: { label: "Contacter l'équipe commerciale", href: "/contact" },
      features: [
        "Références illimitées",
        "Multi-entités et multi-marchés (FR/EU)",
        "Intégration ERP / API dédiée",
        "Audit de conformité annuel offert",
        "SLA garanti 99.9 %",
        "Account manager dédié",
        "Formation équipes incluse",
      ],
    },
  ],
};
